openapi: 3.0.0
info:
  title: Chat API
  description: API for the embedded RAG chatbot in the Physical AI & Humanoid Robotics Book system
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /chat/sessions:
    post:
      summary: Create new chat session
      description: Creates a new chat session for the user
      security:
        - BearerAuth: []
      responses:
        '201':
          description: Chat session created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatSessionResponse'
        '401':
          description: Unauthorized

  /chat/sessions/{sessionId}:
    get:
      summary: Get chat session
      description: Retrieves a specific chat session and its messages
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Chat session retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatSessionWithMessagesResponse'
        '401':
          description: Unauthorized
        '404':
          description: Chat session not found

  /chat/sessions/{sessionId}/messages:
    get:
      summary: Get chat messages
      description: Retrieves messages from a specific chat session
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Chat messages retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChatMessageResponse'
                  total:
                    type: integer

    post:
      summary: Send chat message
      description: Sends a message to the chat session and receives AI response
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageRequest'
      responses:
        '200':
          description: Message processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageResponse'
        '401':
          description: Unauthorized
        '404':
          description: Chat session not found

  /chat/sessions/{sessionId}/messages/context:
    post:
      summary: Set message context
      description: Sets the context for a chat session (e.g., "answer only from selected text")
      security:
        - BearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatContextRequest'
      responses:
        '200':
          description: Context updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatContextResponse'
        '401':
          description: Unauthorized
        '404':
          description: Chat session not found

components:
  schemas:
    ChatSessionResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        is_active:
          type: boolean
        context_metadata:
          type: object
          additionalProperties: true

    ChatSessionWithMessagesResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        is_active:
          type: boolean
        context_metadata:
          type: object
          additionalProperties: true
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ChatMessageResponse'

    ChatMessageRequest:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          description: The message content from the user
        context:
          type: object
          additionalProperties: true
          description: Additional context for the message

    ChatMessageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        session_id:
          type: string
          format: uuid
        sender_type:
          type: string
          enum: [user, ai]
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        message_type:
          type: string
          enum: [question, answer, system]
        sources:
          type: array
          items:
            type: string
          description: Sources referenced in the AI response

    ChatContextRequest:
      type: object
      properties:
        context_type:
          type: string
          enum: [full_book, selected_text, chapter_specific]
          description: Type of context to use for responses
        selected_content_id:
          type: string
          nullable: true
          description: ID of specific content to limit responses to (for selected_text context)
        context_metadata:
          type: object
          additionalProperties: true
          description: Additional context configuration

    ChatContextResponse:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        context_type:
          type: string
          enum: [full_book, selected_text, chapter_specific]
        selected_content_id:
          type: string
          nullable: true
        context_metadata:
          type: object
          additionalProperties: true
        updated_at:
          type: string
          format: date-time

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT