openapi: 3.0.0
info:
  title: Content API
  description: API for managing book content, chapters, and modules in the Physical AI & Humanoid Robotics Book system
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /content/modules:
    get:
      summary: List all modules
      description: Retrieves a list of all book modules
      responses:
        '200':
          description: List of modules retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModuleResponse'

  /content/modules/{moduleId}:
    get:
      summary: Get module by ID
      description: Retrieves a specific module and its chapters
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Module retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModuleWithChaptersResponse'
        '404':
          description: Module not found

  /content/chapters:
    get:
      summary: List all chapters
      description: Retrieves a paginated list of all book chapters
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: module_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of chapters retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedChaptersResponse'

  /content/chapters/{chapterId}:
    get:
      summary: Get chapter by ID
      description: Retrieves a specific chapter with content
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: personalization_level
          in: query
          required: false
          schema:
            type: string
            enum: [beginner, intermediate, advanced]
          description: Personalization level for content adaptation
      responses:
        '200':
          description: Chapter retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChapterResponse'
        '404':
          description: Chapter not found

  /content/chapters/{chapterId}/personalize:
    post:
      summary: Personalize chapter content
      description: Returns personalized version of chapter content based on user profile
      security:
        - BearerAuth: []
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalizeRequest'
      responses:
        '200':
          description: Personalized chapter content returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChapterResponse'
        '401':
          description: Unauthorized
        '404':
          description: Chapter not found

  /content/chapters/{chapterId}/translate:
    post:
      summary: Translate chapter content
      description: Returns translated version of chapter content
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateRequest'
      responses:
        '200':
          description: Translated chapter content returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChapterResponse'
        '404':
          description: Chapter not found

components:
  schemas:
    ModuleResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        slug:
          type: string
        description:
          type: string
        order_number:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ModuleWithChaptersResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        slug:
          type: string
        description:
          type: string
        order_number:
          type: integer
        chapters:
          type: array
          items:
            $ref: '#/components/schemas/ChapterSummary'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ChapterSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        slug:
          type: string
        order_number:
          type: integer
        module_id:
          type: string
          format: uuid

    ChapterResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        slug:
          type: string
        content:
          type: string
        module_id:
          type: string
          format: uuid
        order_number:
          type: integer
        available_languages:
          type: array
          items:
            type: string
        is_personalized:
          type: boolean
        personalization_level:
          type: string
          enum: [beginner, intermediate, advanced]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    PaginatedChaptersResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ChapterSummary'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        has_more:
          type: boolean

    PersonalizeRequest:
      type: object
      required:
        - level
      properties:
        level:
          type: string
          enum: [beginner, intermediate, advanced]
          description: Desired personalization level

    TranslateRequest:
      type: object
      required:
        - target_language
      properties:
        target_language:
          type: string
          description: Target language code (e.g., 'ur' for Urdu)
        preserve_formatting:
          type: boolean
          default: true
          description: Whether to preserve document formatting

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT